name: Sync to Gitee

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Add Gitee remote
      run: git remote add gitee git@gitee.com:WhiteElephant-abc/TouchControllerWiki.git

    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.GITEE_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 700 ~/.ssh
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -t ed25519 gitee.com >> ~/.ssh/known_hosts

    - name: Push to Gitee
      run: |
        git add *.md
        git commit -m "Sync markdown files via GitHub Actions" || true
        git push gitee main:main --force