name: Sync to Gitee

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Add Gitee remote
      run: git remote add gitee git@gitee.com:WhiteElephant-abc/TouchControllerWiki.git

    - name: Configure SSH
      env:
        PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$PRIVATE_KEY" > ~/.ssh/id_ed25519
        chmod 700 ~/.ssh
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -t ed25519 gitee.com >> ~/.ssh/known_hosts

    - name: Filter out markdown files
      run: |
        sudo apt-get update && sudo apt-get install -y git-filter-repo
        git filter-repo --path-glob '*.md' --force

    - name: Push to Gitee
      run: git push gitee main:main --force

